## Malaysia Descriptive Statistics and Correlation Analysis

This notebook examines the Malaysia sample by summarising the main variables and exploring the correlations between them using the cleaned dataset.

In [1]:
import pandas as pd

my1 = pd.read_csv("../data/processed/malaysia_cleaned.csv")

In [2]:
print(my1.columns)

Index(['D_INTERVIEW', 'edu', 'household_income', 'em', 'marriage',
       'victim_self', 'victim_family', 'Q131_cat', 'Q138_cat', 'gender_cat',
       'Q262'],
      dtype='str')

In [9]:
my1.head(20)

,D_INTERVIEW,edu,household_income,em,marriage,victim_self,victim_family,security,harrassment,Q262,gender_bi
0,458070001.0,2.0,2.0,0,0,0,1,2,4,18.0,1
1,458070002.0,0.0,3.0,1,0,0,0,2,4,19.0,0
2,458070003.0,2.0,3.0,1,1,0,0,2,4,49.0,0
3,458070004.0,2.0,5.0,1,1,0,0,4,3,47.0,1
4,458070005.0,6.0,4.0,1,1,0,0,2,3,38.0,1
5,458070006.0,2.0,4.0,1,1,0,0,3,2,44.0,0
6,458070007.0,2.0,3.0,1,0,0,0,2,2,25.0,0
7,458070008.0,2.0,4.0,0,1,0,0,2,4,66.0,1
8,458070009.0,2.0,5.0,1,1,0,0,1,4,41.0,0
9,458070010.0,1.0,4.0,1,1,0,0,2,3,54.0,1
10,458070011.0,6.0,5.0,1,1,0,0,2,3,27.0,0
11,458070012.0,2.0,4.0,0,0,0,0,1,3,18.0,0
12,458070013.0,4.0,6.0,0,0,0,0,1,4,21.0,0
13,458070014.0,1.0,3.0,0,1,1,1,2,4,68.0,0
14,458070015.0,2.0,4.0,1,1,0,0,2,4,34.0,1
15,458070016.0,2.0,4.0,1,1,0,0,2,3,38.0,0
16,458070017.0,5.0,4.0,1,1,0,0,3,3,37.0,0
17,458070018.0,2.0,5.0,1,1,0,0,3,3,32.0,0
18,458070019.0,2.0,3.0,1,0,0,0,3,4,27.0,0
19,458070020.0,2.0,2.0,1,1,0,0,2,3,46.0,0

In [4]:
# Recode men as 0, women as 1 (make men the reference group)
my1["gender_bi"] = my1["gender_cat"].map(
    {
        1:0,
        2:1
    }
)

In [5]:
my1 = my1.drop(columns="gender_cat")

In [ ]:
# Rename Q131_cat as security
my1 = my1.rename(
    columns={"Q131_cat":"security"}
)

# Rename Q138_cat as harrassment
my1 = my1.rename(
    columns={"Q138_cat":"harrassment"}
)

In [13]:
main_vars = ["security", "harassment", "gender_bi"]

my1[main_vars].info() #to see how many non-missing observations, and what are the data types

<class 'pandas.DataFrame'>
RangeIndex: 1313 entries, 0 to 1312
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   security    1313 non-null   int64
 1   harassment  1313 non-null   int64
 2   gender_bi   1313 non-null   int64
dtypes: int64(3)
memory usage: 30.9 KB

In [27]:
# Reverse code security and harassment to make the value more align to their name
my1["security_r"] = 5 - my1["security"]  # Reverse-code security: higher = more secure
my1["harassment_r"] = 5 - my1["harassment"]  # Reverse-code harassment: higher = more frequent harassment

## Perceived Security 

Q131. Could you tell me how secure do you feel these days?

- Very secure — 1
- Quite secure — 2
- Not very secure — 3
- Not at all secure — 4

In [28]:
my1["security_r"].value_counts(dropna=False).sort_index()

security_r
1     72
2    488
3    630
4    123
Name: count, dtype: int64

In [29]:
my1["security_r"].value_counts(normalize=True).sort_index() * 100  # Convert frequencies to percentages

security_r
1     5.483625
2    37.166794
3    47.981721
4     9.367860
Name: proportion, dtype: float64

## Perceived Prevalence of Sexual Harassment
Q138. Sexual harassment
- Very frequently — 1
- Quite frequently — 2
- Not frequently — 3
- Not at all frequently — 4

In [31]:
my1["harassment_r"].value_counts(dropna=False).sort_index()

harassment_r
1    503
2    509
3    217
4     84
Name: count, dtype: int64

In [30]:
my1["harassment_r"].value_counts(normalize=True).sort_index() * 100

harassment_r
1    38.309216
2    38.766184
3    16.527037
4     6.397563
Name: proportion, dtype: float64

## Gender
- Men = 0
- Women = 1

In [20]:
my1["gender_bi"].value_counts(dropna=False).sort_index() # See the distribution of Gender

gender_bi
0    657
1    656
Name: count, dtype: int64

In [21]:
my1["gender_bi"].value_counts(normalize=True).sort_index() * 100 # Calculate gender percentages

gender_bi
0    50.038081
1    49.961919
Name: proportion, dtype: float64

In [32]:
my1.groupby("gender_bi")[["security", "harassment"]].agg(
    ["count", "mean", "std"]
)

          security                     harassment
             count      mean       std      count      mean       std
gender_bi
0              657  2.339422  0.702032        657  3.100457  0.879449
1              656  2.435976  0.756964        656  3.079268  0.906194

## Correlation Tabel

In [34]:
corr_vars = [
    "security_r",
    "harassment_r",
    "gender_bi",
    "edu",
    "household_income",
    "em",
    "marriage",
    "victim_self",
    "victim_family"
]

corr_table = my1[corr_vars].corr(method="spearman").round(3)  # Calculate Spearman correlations
corr_table

,security_r,harassment_r,gender_bi,edu,household_income,em,marriage,victim_self,victim_family
security_r,1.000,-0.376,-0.065,-0.110,-0.094,-0.030,-0.061,-0.121,-0.200
harassment_r,-0.376,1.000,0.008,0.087,0.040,0.026,-0.026,0.244,0.238
gender_bi,-0.065,0.008,1.000,-0.083,-0.033,-0.153,-0.027,0.007,0.042
edu,-0.110,0.087,-0.083,1.000,0.329,0.148,-0.030,0.057,0.077
household_income,-0.094,0.040,-0.033,0.329,1.000,0.191,0.165,0.061,0.057
em,-0.030,0.026,-0.153,0.148,0.191,1.000,0.070,0.061,0.058
marriage,-0.061,-0.026,-0.027,-0.030,0.165,0.070,1.000,-0.036,-0.037
victim_self,-0.121,0.244,0.007,0.057,0.061,0.061,-0.036,1.000,0.434
victim_family,-0.200,0.238,0.042,0.077,0.057,0.058,-0.037,0.434,1.000